language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest

sudo: false

before_script:
  - composer selfupdate
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - phpunit
